title: AkashV22 - There Were 21 Other's Before Him Somehow...
description: A site in the making. Blogs and other stuff, but who knows what'll be here.
repository: AkashV22/akashv22.github.io
lang: en-GB
markdown: kramdown
plugins:
  - jekyll-feed