title: AkashV22 - There Were 21 Others Before Him Somehow...
description: A site in the making. Blogs and other stuff, but who knows what'll be here.
repository: AkashV22/akashv22.github.io
lang: en-GB
markdown: kramdown
permalink: /blog/:year/:month/:day/:title.html
excerpt_separator: <!--more-->
paginate: 5
paginate_path: "/blog/page:num/"
default_search_page: "/search/"
tipue_search:
  include:
    pages: true
plugins:
  - jekyll-feed
exclude:
  - vendor
  - Procfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - _herokuBuildAndServe.sh
  - assets/tipuesearch/css
  - assets/tipuesearch/search.png